// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXi2W3xu64HZtNXgKDq5VUYu5JarYAZug',
    appId: '1:53516137480:web:1852cb521a6aa21295cdbd',
    messagingSenderId: '53516137480',
    projectId: 'scaleup-f0626',
    authDomain: 'scaleup-f0626.firebaseapp.com',
    storageBucket: 'scaleup-f0626.firebasestorage.app',
    measurementId: 'G-QBEFDXQ6L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvp-354Qce7c2wNGvpa4RY-HNM10vjHGE',
    appId: '1:53516137480:android:a38066fd3f224bb095cdbd',
    messagingSenderId: '53516137480',
    projectId: 'scaleup-f0626',
    storageBucket: 'scaleup-f0626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRS0YQnPq0Sj8dlhR6HSDmfzBKPgDSnDc',
    appId: '1:53516137480:ios:0d001dd3460bba3a95cdbd',
    messagingSenderId: '53516137480',
    projectId: 'scaleup-f0626',
    storageBucket: 'scaleup-f0626.firebasestorage.app',
    iosClientId: '53516137480-j2pdr1bllut1b5d3n8sjdqjc01hcar8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.scaleUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRS0YQnPq0Sj8dlhR6HSDmfzBKPgDSnDc',
    appId: '1:53516137480:ios:0d001dd3460bba3a95cdbd',
    messagingSenderId: '53516137480',
    projectId: 'scaleup-f0626',
    storageBucket: 'scaleup-f0626.firebasestorage.app',
    iosClientId: '53516137480-j2pdr1bllut1b5d3n8sjdqjc01hcar8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.scaleUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXi2W3xu64HZtNXgKDq5VUYu5JarYAZug',
    appId: '1:53516137480:web:d3548eac9e5fb6ce95cdbd',
    messagingSenderId: '53516137480',
    projectId: 'scaleup-f0626',
    authDomain: 'scaleup-f0626.firebaseapp.com',
    storageBucket: 'scaleup-f0626.firebasestorage.app',
    measurementId: 'G-ERKXT3KEHT',
  );
}
