const loadingTips = [
  "You can click on the underlined text to view hints on each question!",
  "While not recommended, you can learn locked chapters by clicking on them.",
  "Quick refresher: 1 mile ≈ 1 609 meters.",
  "Remember: 1 kg = 1 000 g and 1 g = 0.001 kg.",
  "Did you know? 1 liter of water has a mass of about 1 kg.",
  "Area shortcut: 1 km² = 1 000 000 m² (that’s a million!).",
  "Temp tip: °F = (°C × 1.8) + 32. Try it: 20 °C → ? °F.",
  "Metric prefixes matter: kilo- is 10³, centi- is 10⁻², milli- is 10⁻³.",
  "Volume check: 1 m³ = 1 000 L.",
  "Energy fact: 1 BTU ≈ 1 055 J (joules).",
  "Pro tip: Round to two significant figures for a quick estimate.",
  "Speed hack: Group similar units—convert mm→cm→m in one go.",
  "Heat energy refresher: 1 cal ≈ 4.184 J.",
  "Fun challenge: How many square meters are in 5 acres? (Hint: 1 ac ≈ 4 047 m²)",
  "Accuracy matters: Double-check your decimal point—it can shift your result by 1 000×!",
  "Conversion memory: 1 inch = 2.54 cm (keep this one handy!).",
  "Volume relation: 1 US gallon ≈ 3.785 liters.",
  "Mass equivalence: 1 pound (lb) ≈ 0.4536 kg.",
  "Temperature trick: To go from °F to °C: (°F - 32) / 1.8.",
  "Area conversion: 1 hectare = 10 000 m².",
  "Energy insight: 1 kWh = 3.6 million joules.",
  "Length ladder: 1 mm → 1 cm → 1 m → 1 km—move the decimal 3 places each step.",
  "Mass milestone: 1 ton (metric) = 1 000 kg.",
  "Volume variety: 1 tablespoon ≈ 15 mL.",
  "Quick fact: 1 cubic centimeter (1 cm³) = 1 milliliter (1 mL).",
  "Did you know? Kelvin is considered a ratio scale, while Celsius is not.",
  "Mind the unit prefixes: 'm' (milli) is 10⁻³ and 'k' (kilo) is 10³. However, micro (µ) is 10⁻⁶.",
  "Shortcut: 1 acre = 4 046.86 m².",
  "Remember: 1 ft = 12 in, so divide inches by 12 to get feet.",
  "Decimal drift: move the decimal three places left/right for mm ↔ km conversions.",
  "Use scientific notation for very large/small values to avoid mistakes (e.g. 1×10⁻³ m).",
  "Calorie context: 1 kcal = 4 184 J.",
  "Freezing point: water freezes at 273.15 K and 32 °F.",
  "1 BTU raises 1 lb of water by 1 °F—handy for quick heat estimates.",
  "1 m³ = 1 000 L = 35.3147 ft³—useful for container volumes.",
  "1 week = 7 days; multiply days by 24 to convert to hours.",
  "Memory hack: think 'kilo' = 1 000 to link any SI conversion quickly.",
  "Milliseconds → seconds: divide by 1 000; hours → seconds: multiply by 3 600.",
  "Convert hectares to acres by dividing by 0.4047.",
  "1 year ≈ 365 days (use 365.25 for leap-year precision).",
  "Kelvin → Rankine: multiply by 1.8 (°R = K × 1.8).",
  "Invert your formula by using the reciprocal factor for the reverse conversion.",
  "Round intermediate results to three significant figures to limit rounding error.",
  "Always write down units during your calculations to keep track.",
  "Practice chaining: e.g. meter → cm → mm → km to build fluency.",
  "Use ratio reasoning: treating conversions as equivalent ratios helps avoid mistakes.",
];
